### ISSUE TITLE
Bruker

### ISSUE THREAD

**Issue by quadwax** [Worzaii/Mafiaspill#2]
Hvordan få admin bruker ?

**Comment by Worzaii** [comment]
Kjør inn følgende spørring mot databasen:
UPDATE `users` SET `status` = 1 WHERE `user` = "ditt brukernavn";

**Comment by quadwax** [comment]
Men må jeg ha bruker fra før for har ikke bruker i det hele tatt for får
ikke laget bruker

**Comment by Worzaii** [comment]
Ja, du må ha en bruker fra før av.

**Comment by quadwax** [comment]
Hvordan får jeg det da. Klarer ikke og få til så jeg får mail for og
registrere meg

**Comment by Worzaii** [comment]
Har du satt opp databasen?

**Comment by quadwax** [comment]
Ja har lasta opp sql filen i xampp

**Comment by Worzaii** [comment]
Har du endret filen som ligger på /classes/class.php og endret info her?

**Comment by quadwax** [comment]
Nei

**Comment by Worzaii** [comment]
Sjekk at du setter riktig brukernavn og passord med tanke på MySQL brukeren din. I dette tilfellet root uten passord

**Comment by quadwax** [comment]
Kommer jo inn på registrering siden hvis jeg går på registrermail.php så
får jeg bare en feil med linken kan kun skrive hvem som vervet meg

**Comment by quadwax** [comment]
Brukernavn og det er rett

**Comment by Worzaii** [comment]
Får du registrering i epost?

**Comment by quadwax** [comment]
Nope

**Comment by Worzaii** [comment]
Sjekk error.log i xampp. Noen feil der?

**Comment by quadwax** [comment]
Nope er ikke det er nok bare jeg som ikke setter det opp riktig

**Comment by Worzaii** [comment]
Du får si ifra hvis du fortsetter å plages, så kan jeg evt. hjelpe deg å sette opp via Teamviewer, eller veilede deg via Skype.

**Comment by quadwax** [comment]
Ok. Har lagt inn alt på nytt men funker enda ikke.

**Comment by Worzaii** [comment]
Hvis du vil, legg til werzaire.

**Comment by quadwax** [comment]
Ok har lagt deg til nå.
