### ISSUE TITLE
[Help wanted] - Contact or other, name it here

### ISSUE THREAD

**Issue by Mollysaurusen** [Worzaii/Mafiaspill#36]
**If you have any issues setting up the game, describe what you've done so far here**
A clear and concise description of what the problem is. Ex. I used git clone to my /var/www/html and [...]

Prøver og bruke koden på en hostgator webserver men når jeg skal laste opp databasen får jeg bare: 
#1273 - Unknown collation: 'utf8mb4_0900_ai_ci'

**List up what packages you've installed on ubuntu, if applicable.**
To list, run this command in a linux shell: _apt list --installed_ and put the results either as an attachment and refer to it here or paste it here.

**How do I contact you outside here?**
If you have a preference to keep in touch on other platforms than this, please supply which platform. Like Telegram, Twitter, Facebook, Discord etc.

RogerWE
#9086

^^
Discord håper og høre fra deg :D

**Comment by Worzaii** [comment]
Installed and set up for Ubuntu 20 with the following:
Apache2 with ssl.
php7.4 with mysql
```
sudo apt-get update
sudo apt -y install software-properties-common
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install -y php7.4-{mysql,common,mbstring}
sudo a2enmod ssl
sudo systemctl reload apache2
```
