### ISSUE TITLE
[Help wanted] - Trenger hjelp

### ISSUE THREAD

**Issue by Mollysaurusen** [Worzaii/Mafiaspill#37]
[Mon Jan 04 08:29:21.709426 2021] [php7:emerg] [pid 19496] [client 185.23.145.113:43034] PHP Parse error:  syntax error, unexpected 'PDO' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/website/public/classes/User.php on line 36

^^
How do i fix

**How do I contact you outside here?**
If you have a preference to keep in touch on other platforms than this, please supply which platform. Like Telegram, Twitter, Facebook, Discord etc.

RogerWE
#9086

**Comment by Worzaii** [comment]
Closing double case from issue #36
