### ISSUE TITLE
Innlogging fungerer ikke

### ISSUE THREAD

**Issue by HappinessPK** [Worzaii/Mafiaspill#6]
Hei, får ikke til å logge inn for en eller annen grunn.

Ingenting skjer når jeg trykker på logg inn. Jeg får derimot beskjed om jeg har skrevet feil passord.

Her er loggen fra netverks inspiseringen
`<br />
<b>Warning</b>:  fopen(feil.txt): failed to open stream: Permission denied in <b>/home/playkit1/public_html/classes/class.php</b> on line <b>98</b><br />
<br />
<b>Warning</b>:  fwrite() expects parameter 1 to be resource, boolean given in <b>/home/playkit1/public_html/classes/class.php</b> on line <b>99</b><br />
<br />
<b>Warning</b>:  fclose() expects parameter 1 to be resource, boolean given in <b>/home/playkit1/public_html/classes/class.php</b> on line <b>100</b><br />
{"string":"<p class=\"lykket\">Du har blitt logget inn! <br \/>Videresender...<\/p>","state":"1"}`

**Comment by Worzaii** [comment]
Hei.

Jeg antar at du kjører linux for å kjøre skriptet, det som kan være feil her er tilgangen til å skrive til feil.txt filen.
Du kan prøve å kjøre følgende kommandoer:

> sudo chown www-data.www-data /home/playkit1/public_html/feil.txt
> sudo chmod 770 /home/playkit1/public_html/feil.txt

**Comment by HappinessPK** [comment]
Fikk hosten min til å prøve men fikk dette til svar "The file that you're trying to use is already owned by the currect user of your website."

**Comment by Worzaii** [comment]
Hvilket operativsystem kjører du?
Hvilken versjon av operativsystemet kjører du?
Hva skjer om du sletter feil.txt filen fra root folder?

**Comment by Worzaii** [comment]
Hei igjen, jeg testet litt rundt og fant feilen.
Jeg bruker Ubuntu som operativsystem.
Når jeg kjørte følgende kommando i Ubuntu så løste det problemet som jeg mistenker du opplever.
Merk, du må endre banen hvis du har root en annen plass.
> sudo chown -R www-data.www-data /var/www/html
